# Generated by Django 4.2 on 2023-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otype', models.CharField(max_length=250, verbose_name='Вид продажи')),
                ('odate', models.DateField(verbose_name='Дата продажи')),
                ('onumb', models.CharField(default='-', max_length=250, verbose_name='Номер кассового аппарата')),
                ('oname', models.CharField(default='-', max_length=250, verbose_name='Имя покупателя')),
                ('oitems', models.CharField(max_length=250, verbose_name='Товары')),
                ('osumm', models.IntegerField(verbose_name='Общая сумма')),
                ('oreason', models.CharField(default='-', max_length=250, verbose_name='Причина возврата')),
                ('ovozn', models.CharField(default='-', max_length=250, verbose_name='Номер документа продажи')),
                ('ovozd', models.CharField(default='-', max_length=250, verbose_name='Дата документа продажи')),
            ],
        ),
    ]
