# Generated by Django 4.2 on 2023-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='odate',
            field=models.DateField(blank=True, default='', max_length=250, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oitems',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oname',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='onumb',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Номер кассового аппарата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='oreason',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Причина возврата'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='osumm',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='otype',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Вид продажи'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ovozd',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Дата документа продажи'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ovozn',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Номер документа продажи'),
        ),
    ]
